#!/bin/bash

services_number=320
max_num=128
iterations=$(( $services_number / $max_num ))
let iterations=$iterations+1
lastservices_count=$(( $services_number % $max_num ))
lowest=1
highest=0
for ((i=1;i<=$iterations;i++)) do 
if [[ "$i" == "$iterations" ]]
then
highest=$(($highest+$lastservices_count))
if [[ "$iterations"== 1 ]]
then
lowest=1
fi
else
highest=$(($highest+$max_num))
fi
lowest=$(($lowest+$max_num)) 
echo lowest $lowest highest $highest
done
