#!/bin/bash
services_number=100
max_num=128
iterations=$(( $services_number / $max_num ))
iterations=$(($iterations + 1 ))
lastservices_count=$(( $services_number % $max_num ))
lowest=1
highest=0
echo iterations $iterations
echo lastservices_count $lastservices_count
for ((i=1;i<=$iterations;i++)) do 
if [[ "$i" == "$iterations" ]]
then
highest=$(($highest + $lastservices_count))
if [[ "$iterations" == 1 ]]
then
lowest=1
fi
else
highest=$(($highest + $max_num))
fi
echo lowest $lowest highest $highest
if (( "$i" >= 1 ))
read -e -i "$new_rule" -p "Please enter the new rule name to services from $lowest to $highest, please make sure that the new rule is already created : " input
new_rule="${input:-$new_rule}"
fi
lowest=$(($lowest + $max_num)) 
done
